packages:
  - examples/*
catalog:
  '@antfu/eslint-config': ^4.3.0
  '@nuxt/devalue': ^2.0.2
  '@types/html-minifier-terser': ^7.0.2
  '@types/jsdom': ^21.1.7
  '@unhead/dom': ^2.0.1
  '@unhead/vue': ^2.0.1
  '@vitejs/plugin-vue': ^5.2.1
  ansis: ^3.15.0
  beasties: ^0.2.0
  bumpp: ^10.0.3
  cac: ^6.7.14
  eslint: ^9.20.1
  html-minifier-terser: ^7.2.0
  html5parser: ^2.0.2
  jsdom: ^26.0.0
  p-queue: ^8.1.0
  pinia: ^3.0.1
  prettier: ^3.5.1
  rollup: ^4.34.8
  tinyglobby: ^0.2.11
  tsx: ^4.19.2
  typescript: 5.6.3
  unbuild: ^3.5.0
  unplugin-vue-components: ^28.2.0
  unplugin-vue-markdown: ^28.3.0
  vite: ^6.1.0
  vite-plugin-pages: ^0.32.4
  vite-plugin-pwa: ^0.21.1
  vitest: ^3.0.5
  vue: ^3.5.13
  vue-router: ^4.5.0
  vue-tsc: ^2.2.2
  yargs: ^17.7.2
