packages:
  - examples/*

shamefullyHoist: true
ignoreWorkspaceRootCheck: true
strictPeerDependencies: false
shellEmulator: true

catalog:
  '@antfu/eslint-config': ^6.0.0
  '@nuxt/devalue': ^2.0.2
  '@types/html-minifier-terser': ^7.0.2
  '@types/jsdom': ^27.0.0
  '@unhead/dom': ^2.0.19
  '@unhead/vue': ^2.0.19
  '@vitejs/plugin-vue': ^6.0.1
  ansis: ^4.2.0
  beasties: ^0.3.5
  bumpp: ^10.3.1
  cac: ^6.7.14
  eslint: ^9.38.0
  html-minifier-terser: ^7.2.0
  html5parser: ^2.0.2
  jsdom: ^27.0.1
  p-queue: ^9.0.0
  pinia: ^3.0.3
  prettier: ^3.6.2
  rollup: ^4.52.5
  tinyglobby: ^0.2.15
  tsx: ^4.20.6
  typescript: ^5.9.3
  unbuild: ^3.6.1
  unplugin-vue-components: ^29.1.0
  unplugin-vue-markdown: ^29.2.0
  vite: ^7.1.10
  vite-plugin-pages: ^0.33.1
  vite-plugin-pwa: ^1.1.0
  vitest: ^3.2.4
  vue: ^3.5.22
  vue-router: ^4.6.3
  vue-tsc: ^3.1.1
  workbox-build: ^7.3.0
onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
