packages:
  - examples/*
catalog:
  '@antfu/eslint-config': ^4.11.0
  '@nuxt/devalue': ^2.0.2
  '@types/html-minifier-terser': ^7.0.2
  '@types/jsdom': ^21.1.7
  '@unhead/dom': ^2.0.2
  '@unhead/vue': ^2.0.2
  '@vitejs/plugin-vue': ^5.2.3
  ansis: ^3.17.0
  beasties: ^0.2.0
  bumpp: ^10.1.0
  cac: ^6.7.14
  eslint: ^9.23.0
  html-minifier-terser: ^7.2.0
  html5parser: ^2.0.2
  jsdom: ^26.0.0
  p-queue: ^8.1.0
  pinia: ^3.0.1
  prettier: ^3.5.3
  rollup: ^4.37.0
  tinyglobby: ^0.2.12
  tsx: ^4.19.3
  typescript: ^5.8.2
  unbuild: ^3.5.0
  unplugin-vue-components: ^28.4.1
  unplugin-vue-markdown: ^28.3.1
  vite: ^6.2.3
  vite-plugin-pages: ^0.32.5
  vite-plugin-pwa: ^1.0.0
  vitest: ^3.0.9
  vue: ^3.5.13
  vue-router: ^4.5.0
  vue-tsc: ^2.2.8
  yargs: ^17.7.2
  workbox-build: ^7.3.0
onlyBuiltDependencies:
  - esbuild
