packages:
  - examples/*
catalog:
  '@antfu/eslint-config': ^5.2.1
  '@nuxt/devalue': ^2.0.2
  '@types/html-minifier-terser': ^7.0.2
  '@types/jsdom': ^21.1.7
  '@unhead/dom': ^2.0.14
  '@unhead/vue': ^2.0.14
  '@vitejs/plugin-vue': ^6.0.1
  ansis: ^4.1.0
  beasties: ^0.3.5
  bumpp: ^10.2.3
  cac: ^6.7.14
  eslint: ^9.34.0
  html-minifier-terser: ^7.2.0
  html5parser: ^2.0.2
  jsdom: ^26.1.0
  p-queue: ^8.1.0
  pinia: ^3.0.3
  prettier: ^3.6.2
  rollup: ^4.50.0
  tinyglobby: ^0.2.14
  tsx: ^4.20.5
  typescript: ^5.9.2
  unbuild: ^3.6.1
  unplugin-vue-components: ^29.0.0
  unplugin-vue-markdown: ^29.1.0
  vite: ^7.1.4
  vite-plugin-pages: ^0.33.1
  vite-plugin-pwa: ^1.0.3
  vitest: ^3.2.4
  vue: ^3.5.20
  vue-router: ^4.5.1
  vue-tsc: ^3.0.6
  workbox-build: ^7.3.0
onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
